//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FMSExpEntities : DbContext
    {
        public FMSExpEntities()
            : base("name=FMSExpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_GST> tbl_GST { get; set; }
        public virtual DbSet<tbl_Items> tbl_Items { get; set; }
        public virtual DbSet<tbl_ItemStock> tbl_ItemStock { get; set; }
        public virtual DbSet<tbl_ItemType> tbl_ItemType { get; set; }
        public virtual DbSet<tbl_ItemUnits> tbl_ItemUnits { get; set; }
        public virtual DbSet<tbl_PaymentMode> tbl_PaymentMode { get; set; }
        public virtual DbSet<tbl_Purchase> tbl_Purchase { get; set; }
        public virtual DbSet<tbl_Sale> tbl_Sale { get; set; }
        public virtual DbSet<tbl_Sequence> tbl_Sequence { get; set; }
        public virtual DbSet<tbl_Transaction> tbl_Transaction { get; set; }
        public virtual DbSet<tbl_vendor> tbl_vendor { get; set; }
        public virtual DbSet<tbl_VendorAddress> tbl_VendorAddress { get; set; }
        public virtual DbSet<tbl_vendorType> tbl_vendorType { get; set; }
        public virtual DbSet<tblMenu> tblMenus { get; set; }
        public virtual DbSet<vw_StockAvailable> vw_StockAvailable { get; set; }
        public virtual DbSet<vw_StockAvailableold> vw_StockAvailableold { get; set; }
        public virtual DbSet<vw_StockDetails> vw_StockDetails { get; set; }
        public virtual DbSet<vw_StockExpirydetails> vw_StockExpirydetails { get; set; }
    }
}
