//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ItemStock
    {
        public int AutoID { get; set; }
        public string ID { get; set; }
        public string StockType { get; set; }
        public string PurchaseID { get; set; }
        public string SaleID { get; set; }
        public string InvoiceNo { get; set; }
        public string ItemID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> PricePerUnit { get; set; }
        public Nullable<decimal> ItemwiseDiscount { get; set; }
        public Nullable<decimal> PricePerUnitAfterDiscount { get; set; }
        public Nullable<decimal> TotalPriceBeforeTax { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> TotalPriceAfterTax { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public Nullable<System.DateTime> Expirydate { get; set; }
        public string BatchNo { get; set; }
        public string CreatedDatetime { get; set; }
    
        public virtual tbl_Items tbl_Items { get; set; }
        public virtual tbl_Purchase tbl_Purchase { get; set; }
        public virtual tbl_Sale tbl_Sale { get; set; }
    }
}
