//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sequence
    {
        public int ID { get; set; }
        public string TableName { get; set; }
        public string PreFix { get; set; }
        public int RecordCount { get; set; }
    }
}
