//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Sale()
        {
            this.tbl_ItemStock = new HashSet<tbl_ItemStock>();
            this.tbl_Transaction = new HashSet<tbl_Transaction>();
        }
    
        public int AutoID { get; set; }
        public string SaleID { get; set; }
        public string InvoiceID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string CustomerID { get; set; }
        public Nullable<decimal> DiscountAfterTax { get; set; }
        public Nullable<decimal> OtherChargeAfterTax { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> TotalValueafterTax { get; set; }
        public Nullable<decimal> RoundOff { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public string CreatedDatetime { get; set; }
        public Nullable<bool> ReverseCharge { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ItemStock> tbl_ItemStock { get; set; }
        public virtual tbl_vendor tbl_vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Transaction> tbl_Transaction { get; set; }
    }
}
