//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Transaction
    {
        public int AutoID { get; set; }
        public string ID { get; set; }
        public string VendorID { get; set; }
        public string PurchaseID { get; set; }
        public string SalesID { get; set; }
        public string EntryID { get; set; }
        public string EntryDate { get; set; }
        public string EntryType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
        public string CreatedDatetime { get; set; }
        public string TransactionType { get; set; }
        public string TransactionRef { get; set; }
    
        public virtual tbl_Purchase tbl_Purchase { get; set; }
        public virtual tbl_Sale tbl_Sale { get; set; }
        public virtual tbl_Transaction tbl_Transaction1 { get; set; }
        public virtual tbl_Transaction tbl_Transaction2 { get; set; }
        public virtual tbl_Transaction tbl_Transaction11 { get; set; }
        public virtual tbl_Transaction tbl_Transaction3 { get; set; }
        public virtual tbl_vendor tbl_vendor { get; set; }
    }
}
