//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VendorAddress
    {
        public int AutoID { get; set; }
        public string ID { get; set; }
        public string vendorID { get; set; }
        public string AddressType { get; set; }
        public string AddLine1 { get; set; }
        public string AddLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PinCode { get; set; }
        public Nullable<int> ContactNo { get; set; }
        public string Email { get; set; }
    
        public virtual tbl_vendor tbl_vendor { get; set; }
    }
}
