//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Purchase()
        {
            this.tbl_ItemStock = new HashSet<tbl_ItemStock>();
            this.tbl_Transaction = new HashSet<tbl_Transaction>();
        }
    
        public int AutoID { get; set; }
        public string ID { get; set; }
        public Nullable<System.DateTime> PartyInvoiceDate { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string PartyInvoiceNo { get; set; }
        public string PartyName { get; set; }
        public string PaymentDueAfter { get; set; }
        public Nullable<bool> ReverseCharge { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> OtherCharge { get; set; }
        public Nullable<decimal> TotalAmountBeforeTax { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> TotalAmountAfterTax { get; set; }
        public Nullable<decimal> RoundOff { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<int> PurchaseBook { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public string ScanCopy { get; set; }
        public string CreatedDatetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ItemStock> tbl_ItemStock { get; set; }
        public virtual tbl_PaymentMode tbl_PaymentMode { get; set; }
        public virtual tbl_vendor tbl_vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Transaction> tbl_Transaction { get; set; }
    }
}
